### PR TITLE
Get back project to working state

### PR DESCRIPTION
**Pull request by mezka**
Added everything from #52 but also added github actions, and tried to fix tests, unfortunately [python-xmlunittest](https://github.com/Exirel/python-xmlunittest) is broken so I went there and made a PR to unbreak it [https://github.com/Exirel/python-xmlunittest/pull/15](https://github.com/Exirel/python-xmlunittest/pull/15).

I fixed the tests, they work on my [python-xmlunittest branch](https://github.com/mezka/python-xmlunittest/tree/fix-broken-lxml) .

We are just waiting for them to merge my changes and then this will work out of the box.

InvoiceGenerator_tests_ok

I integrated github actions, they work now.

github_actions_InvoiceGenerator

They are failing because my changes in python-xmlunittest are still not upstream.

Please kindly merge

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@mezka Thank you very much. The code changes looks simple and straight forward. I will merge this.

The only thing I found - please add all supported Python versions to the GitHub testing to prove older versions are not broken.

**Comment by mezka** [comment]
Ok, I will do the following changes:

- Point the xmlunittest dependency to my forked  xmlunittest repo in order to make the tests run while we wait for upstream merge and pypi release

Because of deprecation older python compatibility may have been broken.

**Comment by mezka** [comment]
Also add older python versions to GitHub actions to find out what versions are broken

**Comment by mezka** [comment]
we_are_finally_green

**Comment by mezka** [comment]
I think this is ready to merge, the sanest thing would be to EOL 3.7 and make a new major release to PyPI

**Comment by mezka** [comment]
*Python 3.7

**Comment by mezka** [comment]
Any updates on merging this code?

**Comment by PetrDlouhy** [comment]
@mezka I everything seems OK. I am only a bit hesitant about merging this with the custom repo for `python-xmlunittest`.
Is there a chance that the fix will reach upstream sometime soon?

**Comment by mezka** [comment]
I sent an email reminder to the python-xmlunittest project dev today.

I'm positive and think upstream merge will happen soon.

**Comment by mezka** [comment]
Please do not close this PR, my xmlunittest fix was merged upstream in [https://github.com/Exirel/python-xmlunittest/](https://github.com/Exirel/python-xmlunittest/) but I'm encountering a new issue with the updated PyPI package, I'm in contact with the repo mantainer and solicited help via email. Hopefully he can test the PyPI package and help me with the sort out the issue.

**Comment by mezka** [comment]
It appears that someone had the same issue with the package update and already made a PR with the fix in upstream, so we are just waiting for that new merge.

**Comment by mezka** [comment]
xmlunittest_upstream_gh_actions_passed

Ok, upstream packaging fix was merged.

I had previously made a couple of commits to try and make a workaround to the upstream packaging bug, but know that upstream is working I resetted HEAD to [56cefde](https://github.com/by-cx/InvoiceGenerator/pull/53/commits/56cefde19a13e356fe18b7466db1c5c6fcc2ecb9)

Now this is ready to merge. Please do, it returns the project to working state, with test suite working and every python version from 3.8 to 3.12 passing the tests

**Comment by PetrDlouhy** [comment]
@mezka Thank you for all your hard work. I am merging this now.

**Pull request merged**
